var searchData=
[
  ['datagramsocket',['DatagramSocket',['../class_poco_1_1_net_1_1_datagram_socket.html',1,'Poco::Net']]],
  ['datagramsocketimpl',['DatagramSocketImpl',['../class_poco_1_1_net_1_1_datagram_socket_impl.html',1,'Poco::Net']]],
  ['datatype',['Datatype',['../structcvflann_1_1_datatype.html',1,'cvflann']]],
  ['datatype_3c_20char_20_3e',['Datatype&lt; char &gt;',['../structcvflann_1_1_datatype_3_01char_01_4.html',1,'cvflann']]],
  ['datatype_3c_20double_20_3e',['Datatype&lt; double &gt;',['../structcvflann_1_1_datatype_3_01double_01_4.html',1,'cvflann']]],
  ['datatype_3c_20float_20_3e',['Datatype&lt; float &gt;',['../structcvflann_1_1_datatype_3_01float_01_4.html',1,'cvflann']]],
  ['datatype_3c_20int_20_3e',['Datatype&lt; int &gt;',['../structcvflann_1_1_datatype_3_01int_01_4.html',1,'cvflann']]],
  ['datatype_3c_20short_20_3e',['Datatype&lt; short &gt;',['../structcvflann_1_1_datatype_3_01short_01_4.html',1,'cvflann']]],
  ['datatype_3c_20unsigned_20char_20_3e',['Datatype&lt; unsigned char &gt;',['../structcvflann_1_1_datatype_3_01unsigned_01char_01_4.html',1,'cvflann']]],
  ['datatype_3c_20unsigned_20int_20_3e',['Datatype&lt; unsigned int &gt;',['../structcvflann_1_1_datatype_3_01unsigned_01int_01_4.html',1,'cvflann']]],
  ['datatype_3c_20unsigned_20short_20_3e',['Datatype&lt; unsigned short &gt;',['../structcvflann_1_1_datatype_3_01unsigned_01short_01_4.html',1,'cvflann']]],
  ['datetime',['DateTime',['../class_poco_1_1_date_time.html',1,'Poco']]],
  ['datetimeformat',['DateTimeFormat',['../class_poco_1_1_date_time_format.html',1,'Poco']]],
  ['datetimeformatter',['DateTimeFormatter',['../class_poco_1_1_date_time_formatter.html',1,'Poco']]],
  ['datetimeparser',['DateTimeParser',['../class_poco_1_1_date_time_parser.html',1,'Poco']]],
  ['debugger',['Debugger',['../class_poco_1_1_debugger.html',1,'Poco']]],
  ['deca',['deca',['../struct_poco_1_1_util_1_1_units_1_1_units_1_1deca.html',1,'Poco::Util::Units::Units']]],
  ['deci',['deci',['../struct_poco_1_1_util_1_1_units_1_1_units_1_1deci.html',1,'Poco::Util::Units::Units']]],
  ['declhandler',['DeclHandler',['../class_poco_1_1_x_m_l_1_1_decl_handler.html',1,'Poco::XML']]],
  ['decompress',['Decompress',['../class_poco_1_1_zip_1_1_decompress.html',1,'Poco::Zip']]],
  ['decryptinginputstream',['DecryptingInputStream',['../class_poco_1_1_crypto_1_1_decrypting_input_stream.html',1,'Poco::Crypto']]],
  ['decryptingoutputstream',['DecryptingOutputStream',['../class_poco_1_1_crypto_1_1_decrypting_output_stream.html',1,'Poco::Crypto']]],
  ['defaulthandler',['DefaultHandler',['../class_poco_1_1_x_m_l_1_1_default_handler.html',1,'Poco::XML']]],
  ['defaultlogger',['DefaultLogger',['../class_assimp_1_1_default_logger.html',1,'Assimp']]],
  ['defaultrngauto',['DefaultRngAuto',['../structcvtest_1_1_default_rng_auto.html',1,'cvtest']]],
  ['defaultstrategy',['DefaultStrategy',['../class_poco_1_1_default_strategy.html',1,'Poco']]],
  ['defaultstrategy_3c_20const_20poco_3a_3aeventargs_2c_20abstractdelegate_3c_20const_20poco_3a_3aeventargs_20_3e_20_3e',['DefaultStrategy&lt; const Poco::EventArgs, AbstractDelegate&lt; const Poco::EventArgs &gt; &gt;',['../class_poco_1_1_default_strategy.html',1,'Poco']]],
  ['defaultstrategy_3c_20const_20poco_3a_3akeyvalueargs_3c_20tkey_2c_20tvalue_20_3e_2c_20abstractdelegate_3c_20const_20poco_3a_3akeyvalueargs_3c_20tkey_2c_20tvalue_20_3e_20_3e_20_3e',['DefaultStrategy&lt; const Poco::KeyValueArgs&lt; TKey, TValue &gt;, AbstractDelegate&lt; const Poco::KeyValueArgs&lt; TKey, TValue &gt; &gt; &gt;',['../class_poco_1_1_default_strategy.html',1,'Poco']]],
  ['defaultstrategy_3c_20const_20poco_3a_3autil_3a_3aabstractconfiguration_3a_3akeyvalue_2c_20abstractdelegate_3c_20const_20poco_3a_3autil_3a_3aabstractconfiguration_3a_3akeyvalue_20_3e_20_3e',['DefaultStrategy&lt; const Poco::Util::AbstractConfiguration::KeyValue, AbstractDelegate&lt; const Poco::Util::AbstractConfiguration::KeyValue &gt; &gt;',['../class_poco_1_1_default_strategy.html',1,'Poco']]],
  ['defaultstrategy_3c_20const_20poco_3a_3azip_3a_3aziplocalfileheader_2c_20abstractdelegate_3c_20const_20poco_3a_3azip_3a_3aziplocalfileheader_20_3e_20_3e',['DefaultStrategy&lt; const Poco::Zip::ZipLocalFileHeader, AbstractDelegate&lt; const Poco::Zip::ZipLocalFileHeader &gt; &gt;',['../class_poco_1_1_default_strategy.html',1,'Poco']]],
  ['defaultstrategy_3c_20const_20std_3a_3astring_2c_20abstractdelegate_3c_20const_20std_3a_3astring_20_3e_20_3e',['DefaultStrategy&lt; const std::string, AbstractDelegate&lt; const std::string &gt; &gt;',['../class_poco_1_1_default_strategy.html',1,'Poco']]],
  ['defaultstrategy_3c_20const_20tkey_2c_20abstractdelegate_3c_20const_20tkey_20_3e_20_3e',['DefaultStrategy&lt; const TKey, AbstractDelegate&lt; const TKey &gt; &gt;',['../class_poco_1_1_default_strategy.html',1,'Poco']]],
  ['defaultstrategy_3c_20keyset_2c_20abstractdelegate_3c_20keyset_20_3e_20_3e',['DefaultStrategy&lt; KeySet, AbstractDelegate&lt; KeySet &gt; &gt;',['../class_poco_1_1_default_strategy.html',1,'Poco']]],
  ['defaultstrategy_3c_20poco_3a_3anet_3a_3aicmpeventargs_2c_20abstractdelegate_3c_20poco_3a_3anet_3a_3aicmpeventargs_20_3e_20_3e',['DefaultStrategy&lt; Poco::Net::ICMPEventArgs, AbstractDelegate&lt; Poco::Net::ICMPEventArgs &gt; &gt;',['../class_poco_1_1_default_strategy.html',1,'Poco']]],
  ['defaultstrategy_3c_20poco_3a_3anet_3a_3averificationerrorargs_2c_20abstractdelegate_3c_20poco_3a_3anet_3a_3averificationerrorargs_20_3e_20_3e',['DefaultStrategy&lt; Poco::Net::VerificationErrorArgs, AbstractDelegate&lt; Poco::Net::VerificationErrorArgs &gt; &gt;',['../class_poco_1_1_default_strategy.html',1,'Poco']]],
  ['defaultstrategy_3c_20poco_3a_3autil_3a_3aabstractconfiguration_3a_3akeyvalue_2c_20abstractdelegate_3c_20poco_3a_3autil_3a_3aabstractconfiguration_3a_3akeyvalue_20_3e_20_3e',['DefaultStrategy&lt; Poco::Util::AbstractConfiguration::KeyValue, AbstractDelegate&lt; Poco::Util::AbstractConfiguration::KeyValue &gt; &gt;',['../class_poco_1_1_default_strategy.html',1,'Poco']]],
  ['defaultstrategy_3c_20poco_3a_3avalidargs_3c_20tkey_20_3e_2c_20abstractdelegate_3c_20poco_3a_3avalidargs_3c_20tkey_20_3e_20_3e_20_3e',['DefaultStrategy&lt; Poco::ValidArgs&lt; TKey &gt;, AbstractDelegate&lt; Poco::ValidArgs&lt; TKey &gt; &gt; &gt;',['../class_poco_1_1_default_strategy.html',1,'Poco']]],
  ['defaultstrategy_3c_20std_3a_3apair_3c_20const_20poco_3a_3azip_3a_3aziplocalfileheader_2c_20const_20poco_3a_3apoco_3a_3apath_20_3e_2c_20abstractdelegate_3c_20std_3a_3apair_3c_20const_20poco_3a_3azip_3a_3aziplocalfileheader_2c_20const_20poco_3a_3apoco_3a_3apath_20_3e_20_3e_20_3e',['DefaultStrategy&lt; std::pair&lt; const Poco::Zip::ZipLocalFileHeader, const Poco::Poco::Path &gt;, AbstractDelegate&lt; std::pair&lt; const Poco::Zip::ZipLocalFileHeader, const Poco::Poco::Path &gt; &gt; &gt;',['../class_poco_1_1_default_strategy.html',1,'Poco']]],
  ['defaultstrategy_3c_20std_3a_3apair_3c_20const_20poco_3a_3azip_3a_3aziplocalfileheader_2c_20const_20std_3a_3astring_20_3e_2c_20abstractdelegate_3c_20std_3a_3apair_3c_20const_20poco_3a_3azip_3a_3aziplocalfileheader_2c_20const_20std_3a_3astring_20_3e_20_3e_20_3e',['DefaultStrategy&lt; std::pair&lt; const Poco::Zip::ZipLocalFileHeader, const std::string &gt;, AbstractDelegate&lt; std::pair&lt; const Poco::Zip::ZipLocalFileHeader, const std::string &gt; &gt; &gt;',['../class_poco_1_1_default_strategy.html',1,'Poco']]],
  ['defaultstrategy_3c_20std_3a_3astring_2c_20abstractdelegate_3c_20std_3a_3astring_20_3e_20_3e',['DefaultStrategy&lt; std::string, AbstractDelegate&lt; std::string &gt; &gt;',['../class_poco_1_1_default_strategy.html',1,'Poco']]],
  ['defaultstrategy_3c_20targs_2c_20abstractdelegate_3c_20targs_20_3e_20_3e',['DefaultStrategy&lt; TArgs, AbstractDelegate&lt; TArgs &gt; &gt;',['../class_poco_1_1_default_strategy.html',1,'Poco']]],
  ['defaultstrategy_3c_20void_2c_20tdelegate_20_3e',['DefaultStrategy&lt; void, TDelegate &gt;',['../class_poco_1_1_default_strategy_3_01void_00_01_t_delegate_01_4.html',1,'Poco']]],
  ['deflatinginputstream',['DeflatingInputStream',['../class_poco_1_1_deflating_input_stream.html',1,'Poco']]],
  ['deflatingios',['DeflatingIOS',['../class_poco_1_1_deflating_i_o_s.html',1,'Poco']]],
  ['deflatingoutputstream',['DeflatingOutputStream',['../class_poco_1_1_deflating_output_stream.html',1,'Poco']]],
  ['deflatingstreambuf',['DeflatingStreamBuf',['../class_poco_1_1_deflating_stream_buf.html',1,'Poco']]],
  ['delegate',['Delegate',['../class_poco_1_1_delegate.html',1,'Poco']]],
  ['delegate_3c_20tobj_2c_20targs_2c_20false_20_3e',['Delegate&lt; TObj, TArgs, false &gt;',['../class_poco_1_1_delegate_3_01_t_obj_00_01_t_args_00_01false_01_4.html',1,'Poco']]],
  ['delegate_3c_20tobj_2c_20void_2c_20false_20_3e',['Delegate&lt; TObj, void, false &gt;',['../class_poco_1_1_delegate_3_01_t_obj_00_01void_00_01false_01_4.html',1,'Poco']]],
  ['delegate_3c_20tobj_2c_20void_2c_20true_20_3e',['Delegate&lt; TObj, void, true &gt;',['../class_poco_1_1_delegate_3_01_t_obj_00_01void_00_01true_01_4.html',1,'Poco']]],
  ['delete',['Delete',['../class_poco_1_1_zip_1_1_delete.html',1,'Poco::Zip']]],
  ['des_5fks',['DES_ks',['../struct_d_e_s__ks.html',1,'']]],
  ['deviceinfo',['DeviceInfo',['../classcv_1_1gpu_1_1_device_info.html',1,'cv::gpu']]],
  ['deviceinfo',['DeviceInfo',['../struct_rt_audio_1_1_device_info.html',1,'RtAudio']]],
  ['devmem2d_5f',['DevMem2D_',['../structcv_1_1gpu_1_1_dev_mem2_d__.html',1,'cv::gpu']]],
  ['dh_5fmethod',['dh_method',['../structdh__method.html',1,'']]],
  ['dh_5fst',['dh_st',['../structdh__st.html',1,'']]],
  ['dialogsocket',['DialogSocket',['../class_poco_1_1_net_1_1_dialog_socket.html',1,'Poco::Net']]],
  ['dict',['Dict',['../struct_dict.html',1,'']]],
  ['dictnode',['DictNode',['../struct_dict_node.html',1,'']]],
  ['digestbuf',['DigestBuf',['../class_poco_1_1_digest_buf.html',1,'Poco']]],
  ['digestengine',['DigestEngine',['../class_poco_1_1_digest_engine.html',1,'Poco']]],
  ['digestinputstream',['DigestInputStream',['../class_poco_1_1_digest_input_stream.html',1,'Poco']]],
  ['digestios',['DigestIOS',['../class_poco_1_1_digest_i_o_s.html',1,'Poco']]],
  ['digestoutputstream',['DigestOutputStream',['../class_poco_1_1_digest_output_stream.html',1,'Poco']]],
  ['directoryiterator',['DirectoryIterator',['../class_poco_1_1_directory_iterator.html',1,'Poco']]],
  ['directoryiteratorimpl',['DirectoryIteratorImpl',['../class_poco_1_1_directory_iterator_impl.html',1,'Poco']]],
  ['disparitybilateralfilter',['DisparityBilateralFilter',['../classcv_1_1gpu_1_1_disparity_bilateral_filter.html',1,'cv::gpu']]],
  ['dist_5fpoint_5fname_5fst',['DIST_POINT_NAME_st',['../struct_d_i_s_t___p_o_i_n_t___n_a_m_e__st.html',1,'']]],
  ['dist_5fpoint_5fst',['DIST_POINT_st',['../struct_d_i_s_t___p_o_i_n_t__st.html',1,'']]],
  ['distindex',['DistIndex',['../structcvflann_1_1_unique_result_set_1_1_dist_index.html',1,'cvflann::UniqueResultSet']]],
  ['dns',['DNS',['../class_poco_1_1_net_1_1_d_n_s.html',1,'Poco::Net']]],
  ['document',['Document',['../class_poco_1_1_x_m_l_1_1_document.html',1,'Poco::XML']]],
  ['documentevent',['DocumentEvent',['../class_poco_1_1_x_m_l_1_1_document_event.html',1,'Poco::XML']]],
  ['documentfragment',['DocumentFragment',['../class_poco_1_1_x_m_l_1_1_document_fragment.html',1,'Poco::XML']]],
  ['documenttype',['DocumentType',['../class_poco_1_1_x_m_l_1_1_document_type.html',1,'Poco::XML']]],
  ['dombuilder',['DOMBuilder',['../class_poco_1_1_x_m_l_1_1_d_o_m_builder.html',1,'Poco::XML']]],
  ['domexception',['DOMException',['../class_poco_1_1_x_m_l_1_1_d_o_m_exception.html',1,'Poco::XML']]],
  ['domimplementation',['DOMImplementation',['../class_poco_1_1_x_m_l_1_1_d_o_m_implementation.html',1,'Poco::XML']]],
  ['domobject',['DOMObject',['../class_poco_1_1_x_m_l_1_1_d_o_m_object.html',1,'Poco::XML']]],
  ['domparser',['DOMParser',['../class_poco_1_1_x_m_l_1_1_d_o_m_parser.html',1,'Poco::XML']]],
  ['domserializer',['DOMSerializer',['../class_poco_1_1_x_m_l_1_1_d_o_m_serializer.html',1,'Poco::XML']]],
  ['domwriter',['DOMWriter',['../class_poco_1_1_x_m_l_1_1_d_o_m_writer.html',1,'Poco::XML']]],
  ['dsa_5fmethod',['dsa_method',['../structdsa__method.html',1,'']]],
  ['dsa_5fsig_5fst',['DSA_SIG_st',['../struct_d_s_a___s_i_g__st.html',1,'']]],
  ['dsa_5fst',['dsa_st',['../structdsa__st.html',1,'']]],
  ['dso_5fmeth_5fst',['dso_meth_st',['../structdso__meth__st.html',1,'']]],
  ['dso_5fst',['dso_st',['../structdso__st.html',1,'']]],
  ['dsp',['DSP',['../class_f_m_o_d_1_1_d_s_p.html',1,'FMOD']]],
  ['dspconnection',['DSPConnection',['../class_f_m_o_d_1_1_d_s_p_connection.html',1,'FMOD']]],
  ['dtdhandler',['DTDHandler',['../class_poco_1_1_x_m_l_1_1_d_t_d_handler.html',1,'Poco::XML']]],
  ['dtdmap',['DTDMap',['../class_poco_1_1_x_m_l_1_1_d_t_d_map.html',1,'Poco::XML']]],
  ['dtls1_5fbitmap_5fst',['dtls1_bitmap_st',['../structdtls1__bitmap__st.html',1,'']]],
  ['dtls1_5frecord_5fdata_5fst',['dtls1_record_data_st',['../structdtls1__record__data__st.html',1,'']]],
  ['dtls1_5fretransmit_5fstate',['dtls1_retransmit_state',['../structdtls1__retransmit__state.html',1,'']]],
  ['dtls1_5fstate_5fst',['dtls1_state_st',['../structdtls1__state__st.html',1,'']]],
  ['dtls1_5ftimeout_5fst',['dtls1_timeout_st',['../structdtls1__timeout__st.html',1,'']]],
  ['dynamicany',['DynamicAny',['../class_poco_1_1_dynamic_any.html',1,'Poco']]],
  ['dynamicanyholder',['DynamicAnyHolder',['../class_poco_1_1_dynamic_any_holder.html',1,'Poco']]],
  ['dynamicanyholderimpl',['DynamicAnyHolderImpl',['../class_poco_1_1_dynamic_any_holder_impl.html',1,'Poco']]],
  ['dynamicanyholderimpl_3c_20bool_20_3e',['DynamicAnyHolderImpl&lt; bool &gt;',['../class_poco_1_1_dynamic_any_holder_impl_3_01bool_01_4.html',1,'Poco']]],
  ['dynamicanyholderimpl_3c_20char_20_3e',['DynamicAnyHolderImpl&lt; char &gt;',['../class_poco_1_1_dynamic_any_holder_impl_3_01char_01_4.html',1,'Poco']]],
  ['dynamicanyholderimpl_3c_20data_3a_3ablob_20_3e',['DynamicAnyHolderImpl&lt; Data::BLOB &gt;',['../class_poco_1_1_dynamic_any_holder_impl_3_01_data_1_1_b_l_o_b_01_4.html',1,'Poco']]],
  ['dynamicanyholderimpl_3c_20datetime_20_3e',['DynamicAnyHolderImpl&lt; DateTime &gt;',['../class_poco_1_1_dynamic_any_holder_impl_3_01_date_time_01_4.html',1,'Poco']]],
  ['dynamicanyholderimpl_3c_20double_20_3e',['DynamicAnyHolderImpl&lt; double &gt;',['../class_poco_1_1_dynamic_any_holder_impl_3_01double_01_4.html',1,'Poco']]],
  ['dynamicanyholderimpl_3c_20float_20_3e',['DynamicAnyHolderImpl&lt; float &gt;',['../class_poco_1_1_dynamic_any_holder_impl_3_01float_01_4.html',1,'Poco']]],
  ['dynamicanyholderimpl_3c_20int16_20_3e',['DynamicAnyHolderImpl&lt; Int16 &gt;',['../class_poco_1_1_dynamic_any_holder_impl_3_01_int16_01_4.html',1,'Poco']]],
  ['dynamicanyholderimpl_3c_20int32_20_3e',['DynamicAnyHolderImpl&lt; Int32 &gt;',['../class_poco_1_1_dynamic_any_holder_impl_3_01_int32_01_4.html',1,'Poco']]],
  ['dynamicanyholderimpl_3c_20int64_20_3e',['DynamicAnyHolderImpl&lt; Int64 &gt;',['../class_poco_1_1_dynamic_any_holder_impl_3_01_int64_01_4.html',1,'Poco']]],
  ['dynamicanyholderimpl_3c_20int8_20_3e',['DynamicAnyHolderImpl&lt; Int8 &gt;',['../class_poco_1_1_dynamic_any_holder_impl_3_01_int8_01_4.html',1,'Poco']]],
  ['dynamicanyholderimpl_3c_20localdatetime_20_3e',['DynamicAnyHolderImpl&lt; LocalDateTime &gt;',['../class_poco_1_1_dynamic_any_holder_impl_3_01_local_date_time_01_4.html',1,'Poco']]],
  ['dynamicanyholderimpl_3c_20long_20_3e',['DynamicAnyHolderImpl&lt; long &gt;',['../class_poco_1_1_dynamic_any_holder_impl_3_01long_01_4.html',1,'Poco']]],
  ['dynamicanyholderimpl_3c_20std_3a_3astring_20_3e',['DynamicAnyHolderImpl&lt; std::string &gt;',['../class_poco_1_1_dynamic_any_holder_impl_3_01std_1_1string_01_4.html',1,'Poco']]],
  ['dynamicanyholderimpl_3c_20std_3a_3avector_3c_20t_20_3e_20_3e',['DynamicAnyHolderImpl&lt; std::vector&lt; T &gt; &gt;',['../class_poco_1_1_dynamic_any_holder_impl_3_01std_1_1vector_3_01_t_01_4_01_4.html',1,'Poco']]],
  ['dynamicanyholderimpl_3c_20timestamp_20_3e',['DynamicAnyHolderImpl&lt; Timestamp &gt;',['../class_poco_1_1_dynamic_any_holder_impl_3_01_timestamp_01_4.html',1,'Poco']]],
  ['dynamicanyholderimpl_3c_20uint16_20_3e',['DynamicAnyHolderImpl&lt; UInt16 &gt;',['../class_poco_1_1_dynamic_any_holder_impl_3_01_u_int16_01_4.html',1,'Poco']]],
  ['dynamicanyholderimpl_3c_20uint32_20_3e',['DynamicAnyHolderImpl&lt; UInt32 &gt;',['../class_poco_1_1_dynamic_any_holder_impl_3_01_u_int32_01_4.html',1,'Poco']]],
  ['dynamicanyholderimpl_3c_20uint64_20_3e',['DynamicAnyHolderImpl&lt; UInt64 &gt;',['../class_poco_1_1_dynamic_any_holder_impl_3_01_u_int64_01_4.html',1,'Poco']]],
  ['dynamicanyholderimpl_3c_20uint8_20_3e',['DynamicAnyHolderImpl&lt; UInt8 &gt;',['../class_poco_1_1_dynamic_any_holder_impl_3_01_u_int8_01_4.html',1,'Poco']]],
  ['dynamicanyholderimpl_3c_20unsigned_20long_20_3e',['DynamicAnyHolderImpl&lt; unsigned long &gt;',['../class_poco_1_1_dynamic_any_holder_impl_3_01unsigned_01long_01_4.html',1,'Poco']]],
  ['dynamicbitset',['DynamicBitset',['../class_dynamic_bitset.html',1,'']]],
  ['dynamicfactory',['DynamicFactory',['../class_poco_1_1_dynamic_factory.html',1,'Poco']]],
  ['dynamicfactory_3c_20poco_3a_3achannel_20_3e',['DynamicFactory&lt; Poco::Channel &gt;',['../class_poco_1_1_dynamic_factory.html',1,'Poco']]],
  ['dynamicfactory_3c_20poco_3a_3aformatter_20_3e',['DynamicFactory&lt; Poco::Formatter &gt;',['../class_poco_1_1_dynamic_factory.html',1,'Poco']]]
];
